### ISSUE TITLE
Design Frequency

### ISSUE THREAD

**Issue by kdotom** [JesseLu/objective-first#1]
RE: example.m
Regarding the line % *   a design frequency of 0.15,

What is the conversion factor between the design frequency in the script and a vacuum wavelength (nm)? There appears to be a scaling factor even after typical conversion to angular frequency, but I'm not clear on what it is.

Thanks!

**Comment by JesseLu** [comment]
The "unitless" system is used, where epsilon_0 = mu_0 = c = 1. See the MEEP
reference at
https://meep.readthedocs.io/en/latest/Introduction/#units-in-meep

**Comment by kdotom** [comment]
Got it. Thanks!
From the example, it appears that for a = 1 μm and λ = 1.55 μm, f as 1/1.55 = 0.6452.

It also seems that to design a device to a certain width, I have to scale the design frequency by the ratio of the nearest possible waveguide width to the desired width (based on the grid element size - can this be modified? / where?) and then scale it down after I export the device. Is there another way?

Side note, should I be using ob-1 as the updated version of this program?
